server:
  port: 9068

spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/download_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&tinyInt1isBit=false&serverTimezone=GMT%2b8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: "SELECT 'x'"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: "stat,wall,log4j"
      connection-properties: "druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000"
      use-global-data-source-stat: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test

mybatis:
  mapperLocations: classpath:mappers/*.xml

logging:
  path: /logging-path 
  file: iDownload.log
